version: '3.6'
services:
  app:
    image: cs
    container_name: app
    depends_on:
      - rd
      - bc
      - cl
    build: .
    command: "bun run dev"
    environment:
      NODE_ENV: development
    ports:
      - '3119:3119'
    volumes:
      - ./:/app
      - ./logs:/logs
    restart: always
  bc:
    image: asoltys/bitcoin
    container_name: bc
    volumes:
      - ./data/bitcoin:/home/bitcoin/.bitcoin
    restart: always
  cl:
    image: elementsproject/lightningd:latest
    container_name: cl
    environment:
      LIGHTNINGD_NETWORK: regtest
    volumes:
      - ./data/lightning:/root/.lightning
    restart: always
  rd:
    image: eqalpha/keydb
    container_name: rd
    volumes:
      - ./data/redis:/data
    restart: always
  nostr:
    container_name: nostr
    image: asoltys/nostr-rs-relay
    restart: always
    user: 100:100
    volumes:
      - "./data/nostr/data:/usr/src/app/db" 
      - "./data/nostr/data.toml:/usr/src/app/config.toml" 
    ports:
      - '8080:8080'
