version: '3.6'
services:
  ui:
    depends_on:
      - app
    container_name: ui
    image: asoltys/coinos-ui:dev
    ports:
      - '8085:8085'
    environment:
      NODE_ENV: development
      NODE_OPTIONS: --openssl-legacy-provider
    volumes:
      - ../coinos-ui:/coinos-ui
  electrsb:
    image: ghcr.io/vulpemventures/electrs
    container_name: electrsb
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --network
      - regtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - bitcoin:18443
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:3095
      - --electrum-rpc-addr
      - 0.0.0.0:60400
      - --cors
      - "*"
    volumes:
      - ./config/bitcoin/:/config
    restart: unless-stopped
    ports:
      - 3095:3095
  electrs-liquid:
    image: asoltys/electrs-liquid:latest
    container_name: electrs
    depends_on:
      - liquid
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --parent-network
      - regtest
      - --network
      - liquidregtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - liquid:7040
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:3002
      - --electrum-rpc-addr
      - 0.0.0.0:60401
      - --cors
      - "*"
    ports:
      - ${LIQUID_ELECTRS_RPC_PORT}:60401
      - ${LIQUID_ELECTRS_PORT}:3002
    volumes:
      - ./config/liquid/:/config
    restart: unless-stopped
  esplora-liquid:
    image: vulpemventures/esplora:latest
    container_name: esplora-liquid
    depends_on:
      - electrs-liquid
    environment:
      API_URL: ${LIQUID_ELECTRS_URL}
      NATIVE_ASSET_ID: 5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225
      IS_ELEMENTS: 1
    ports:
      - ${LIQUID_ESPLORA_PORT}:5000
    restart: unless-stopped
  clightning:
    image: asoltys/lightning
    container_name: cl
    environment:
      LIGHTNINGD_NETWORK: regtest
    volumes:
      - ./config/lightning:/root/.lightning
    restart: unless-stopped
