version: '3.6'
services:
  clapp:
    depends_on:
      - cl
      - maria
      - bc
      - lq
    container_name: clapp
    image: gcr.io/coinos-326717/github.com/coinos/coinos-server:prod
    restart: always
    environment:
      NODE_ENV: production
      NODE_OPTIONS: "--es-module-specifier-resolution=node --experimental-modules --loader ./loader.js --openssl-legacy-provider"
      HOSTNAME: "${HOSTNAME}"
    volumes:
      - ./:/app
      - ./logs:/logs
    networks:
      default:
        ipv4_address: 172.42.0.22
  maria:
    container_name: maria
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
  bc:
    image: asoltys/bitcoin
    container_name: bc
    volumes:
      - ./config/bitcoin:/home/bitcoin/.bitcoin
    restart: always
    networks:
      default:
        ipv4_address: 172.42.0.23
  lq:
    image: ghcr.io/vulpemventures/elements
    container_name: lq
    volumes:
      - ./config/liquid:/home/elements/.elements
    restart: always
    networks:
      default:
        ipv4_address: 172.42.0.24
  cl:
    depends_on:
      - bc
    image: elementsproject/lightningd:v22.11.1
    container_name: cl
    restart: always
    volumes:
      - ./config/lightning:/root/.lightning
    ports:
      - "9736:9735"
    networks:
      default:
        ipv4_address: 172.42.0.25
  lnd:
    depends_on:
      - bc
      - tor 
    image: lightninglabs/lnd:v0.15.4-beta
    container_name: lnd
    volumes:
      - ./config/lnd:/root/.lnd
      - ./config/bitcoin:/root/.bitcoin
      - ./config/tor:/etc/tor
    ports:
      - "9735:9735"
    restart: always
    networks:
      default:
        ipv4_address: 172.42.0.26
  tor:
    container_name: tor
    image: dperson/torproxy
    restart: always
    volumes:
      - ./config/tor:/etc/tor
      - ./config/tordata:/var/lib/tor
    networks:
      default:
        ipv4_address: 172.42.0.27
  redis:
    restart: always
    container_name: redis
    image: redis
    volumes:
      - ./config/redis:/data
networks:
  default:
    name: net
    external: true
