version: '3.6'
services:
  ui:
    depends_on:
      - app
    container_name: ui
    image: asoltys/coinos-ui:dev
    ports:
      - '8085:8085'
    environment:
      NODE_ENV: development
    volumes:
      - ../coinos-ui:/app
    networks:
      default:
        ipv4_address: 172.18.0.27
  app:
    depends_on:
      - maria
      - bitcoin
      - liquid
      - lnd
    container_name: app
    image: gcr.io/coinos-326717/github.com/coinos/coinos-server:prod
    command: "pnpm dev"
    ports:
      - '3119:3119'
    environment:
      NODE_OPTIONS: "--es-module-specifier-resolution=node --experimental-modules --loader ./loader.js --openssl-legacy-provider"
      NODE_ENV: development
    volumes:
      - ./:/app
      - ./logs:/logs
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      default:
        ipv4_address: 172.18.0.22
  bitcoin:
    image: ghcr.io/vulpemventures/bitcoin
    container_name: bitcoin
    volumes:
      - ./config/bitcoin:/home/bitcoin/.bitcoin
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.23
  liquid:
    image: ghcr.io/vulpemventures/elements
    container_name: liquid
    volumes:
      - ./config/liquid:/home/elements/.elements
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.24
  lnd:
    image: lightninglabs/lnd:v0.15.1-beta
    container_name: lnd
    volumes:
      - ./config/lnd:/root/.lnd
      - ./config/bitcoin:/root/.bitcoin
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.25
  clightning:
    image: elementsproject/lightningd:v0.12.0
    container_name: cl
    environment:
      LIGHTNINGD_NETWORK: regtest
    volumes:
      - ./config/lightning:/root/.lightning
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.31
  maria:
    container_name: maria
    image: mariadb:10.6.1
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      default:
        ipv4_address: 172.18.0.26
  electrsb:
    depends_on:
      - bitcoin
    image: ghcr.io/vulpemventures/electrs
    container_name: electrsb
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --network
      - regtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - bitcoin:18443
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:3095
      - --electrum-rpc-addr
      - 0.0.0.0:60400
      - --cors
      - "*"
    volumes:
      - ./config/bitcoin/:/config
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.28
  electrs-liquid:
    image: ghcr.io/vulpemventures/electrs-liquid
    container_name: electrs
    depends_on:
      - liquid
    entrypoint:
      - /build/electrs
    command:
      - --jsonrpc-import
      - -vvvv
      - --parent-network
      - regtest
      - --network
      - liquidregtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - liquid:7040
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:3002
      - --electrum-rpc-addr
      - 0.0.0.0:60401
      - --cors
      - "*"
    volumes:
      - ./config/liquid/:/config
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.29
  esplora-liquid:
    image: vulpemventures/esplora:latest
    container_name: esplora-liquid
    depends_on:
      - electrs-liquid
    environment:
      API_URL: ${LIQUID_ELECTRS_URL}
      NATIVE_ASSET_ID: 5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225
      IS_ELEMENTS: 1
    ports:
      - ${LIQUID_ESPLORA_PORT}:5000
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.30
  spark:
    image: shesek/spark-wallet:standalone
    container_name: spark
    volumes:
      - ./config/spark:/data
      - ./config/lightning/regtest:/etc/lightning
    ports:
      - '9737:9737'
    environment:
      LOGIN: "${LOGIN}"
      NO_TLS: "${NO_TLS}"
    networks:
      default:
        ipv4_address: 172.18.0.32
networks: 
  default: 
    name: net
    external: true
