version: '3.6'
services:
  app:
    depends_on:
      - maria
    container_name: app
    image: asoltys/coinos-server
    restart: on-failure
    environment:
      HASURA_SECRET:  '${HASURA_GRAPHQL_ADMIN_SECRET}'
      CLOUDFLARE_TOKEN: '${CLOUDFLARE_TOKEN}'
      CLOUDFLARE_ZONE: '${CLOUDFLARE_ZONE}'
      DOMAIN: '${DOMAIN}'
      COINOS_URL: '${COINOS_URL}'
      COINOS_TOKEN: '${COINOS_TOKEN}'
      HASURA_URL: '${HASURA_URL}'
      HASURA_JWT: '${HASURA_GRAPHQL_JWT_SECRET}'
      LIQUID_ELECTRS_URL: '${LIQUID_ELECTRS_URL}'
      HBP_URL: '${HBP_URL}'
      IPFS_URL: '${IPFS_URL}'
      IPFS_WEB_URL: '${IPFS_WEB_URL}'
      SIGNING_SERVER_MNEMONIC: '${SIGNING_SERVER_MNEMONIC}'
    ports:
      - '8091:8091'
      - '8092:8092'
    volumes:
      - ./config:/app/config
  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - ${DATA_DIR}:/var/lib/postgresql/data
    ports:
      - '5433:5432'
  hasura:
    container_name: hasura
    image: hasura/graphql-engine:v1.3.3
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./migrations:/hasura-migrations
      - ./metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET:  '${HASURA_GRAPHQL_ADMIN_SECRET}'
      HASURA_GRAPHQL_JWT_SECRET: '${HASURA_GRAPHQL_JWT_SECRET}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
  hbp:
    container_name: hbp
    image: nhost/hasura-backend-plus:latest
    depends_on:
      - hasura
    ports:
      - '3400:3000'
    environment:
      SERVER_URL: '${SERVER_URL}'
      HASURA_ENDPOINT: '${HASURA_URL}/v1/graphql'
      HASURA_GRAPHQL_ADMIN_SECRET:  '${HASURA_GRAPHQL_ADMIN_SECRET}'
      JWT_ALGORITHM: '${JWT_ALGORITHM}'
      JWT_KEY: '${JWT_KEY}'
      AUTO_MIGRATE: "true"
      AUTO_ACTIVATE_NEW_USERS: "false"
      STORAGE_ENABLE: "false"
      MAX_REQUESTS: 10000
      LOST_PASSWORD_ENABLE: "true"
      EMAILS_ENABLE: "true"
      SMTP_HOST: '${SMTP_HOST}'
      SMTP_PORT: '${SMTP_PORT}'
      SMTP_USER: '${SMTP_USER}'
      SMTP_PASS: '${SMTP_PASS}'
      SMTP_SENDER: '${SMTP_SENDER}'
    volumes:
      - ./custom:/app/custom
  ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs
    ports:
      - 8081:8080
      - 4001:4001
      - 5001:5001
    volumes:
      - ${IPFS_DATA}:/data/ipfs
      - ${STORAGE_DIR}:/export
  bitcoin:
    image: asoltys/bitcoin:latest
    container_name: bitcoin
    ports:
      - ${BITCOIN_PEER_PORT}:19000
      - ${BITCOIN_NODE_PORT}:19001
    volumes:
      - ./liquidregtest/config/:/config
    restart: unless-stopped
  liquid:
    image: asoltys/liquid:latest
    container_name: liquid
    ports:
      - ${LIQUID_NODE_PORT}:18884
      - ${LIQUID_PEER_PORT}:18886
      - ${LIQUID_BLOCK_PORT}:18602
      - ${LIQUID_TX_PORT}:18603
    volumes:
      - ./liquidregtest/liquid-config/:/config
    restart: unless-stopped
  electrs-liquid:
    image: vulpemventures/electrs-liquid:latest
    container_name: electrs-liquid
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --parent-network
      - regtest
      - --network
      - liquidregtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - liquid:18884
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:3002
      - --electrum-rpc-addr
      - 0.0.0.0:60401
      - --cors
      - "*"
    depends_on:
      - liquid
    ports:
      - ${LIQUID_ELECTRS_RPC_PORT}:60401
      - ${LIQUID_ELECTRS_PORT}:3002
    volumes:
      - ./liquidregtest/liquid-config/:/config
    restart: unless-stopped
  esplora-liquid:
    image: vulpemventures/esplora:latest
    container_name: esplora-liquid
    environment:
      API_URL: ${LIQUID_ELECTRS_URL}
      NATIVE_ASSET_ID: 5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225
      IS_ELEMENTS: 1
    ports:
      - ${LIQUID_ESPLORA_PORT}:5000
    restart: unless-stopped
