apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: electrs-liquid
  name: electrs-liquid
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: electrs-liquid
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: electrs-liquid
    spec:
      containers:
        - args:
            - -vvvv
            - --parent-network
            - regtest
            - --network
            - liquidregtest
            - --daemon-dir
            - /config
            - --daemon-rpc-addr
            - liquid:7040
            - --cookie
            - admin1:123
            - --http-addr
            - 0.0.0.0:3002
            - --electrum-rpc-addr
            - 0.0.0.0:60401
            - --cors
            - '*'
          command:
            - /build/electrs
          image: vulpemventures/electrs-liquid:latest
          name: electrs-liquid
          ports:
            - containerPort: 60401
            - containerPort: 3002
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: electrs-liquid-claim0
      restartPolicy: Always
      volumes:
        - name: electrs-liquid-claim0
          persistentVolumeClaim:
            claimName: electrs-liquid-claim0
status: {}
